# Generated by Django 5.2.6 on 2025-09-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caryard', '0002_seller_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
