# Generated by Django 5.2.6 on 2025-09-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caryard', '0003_seller_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
