# Generated by Django 5.2.6 on 2025-10-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caryard', '0010_staff_booking_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=1000),
        ),
    ]
