# Generated by Django 5.2.6 on 2026-06-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caryard', '0014_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(blank=True, default='staff', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
